import Script from "next/script";
import "bootstrap/dist/css/bootstrap.min.css";
import {
  Geist,
  Geist_Mono,
  Architects_Daughter,
  Playfair_Display,
} from "next/font/google";

//TODO- få hamburgarmenyn at fungera
import "./globals.css";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Saras CMS-projekt",
  description: "Generated by create next app",
};

const architectsDaughter = Architects_Daughter({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-architects-daughter",
});

const playfairDisplay = Playfair_Display({
  subsets: ["latin"],
  variable: "--font-playfair-display",
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${architectsDaughter.variable} ${playfairDisplay.variable}`}
      >
        {children}
        <Script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.min.js"></Script>
      </body>
    </html>
  );
}
